CREATE TABLE LINK_POOL
(
    LINK VARCHAR(1000)
);
CREATE TABLE PROCESSED_LINK_POOL
(
    LINK VARCHAR(1000)
);
CREATE TABLE NEWS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE TEXT,
    CONTENT TEXT,
    URL VARCHAR(1000),
    CREATED_AT TIMESTAMP,
    MODIFIED_AT TIMESTAMP
)