CREATE TABLE LINK_POOL
(
    LINK VARCHAR(1000)
);
CREATE TABLE PROCESSED_LINK_POOL
(
    LINK VARCHAR(1000)
);
CREATE TABLE NEWS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE TEXT,
    CONTENT TEXT,
    URL VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    MODIFIED_AT TIMESTAMP DEFAULT NOW()
);
ALTER DATABASE news CHARACTER SET =utf8mb4;
ALTER TABLE NEWS CHARACTER SET =utf8mb4